# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0a16b450a93cc07ff4f97f89dd8feb0a69d10841b908413a67afb44ac342781b8be649f5dba6037279294517319e1465700c51c324213f0f950f5bf88c70596

test:
  secret_key_base: c6236c206b415dc89f46043cd4155a249b2d314b3ae5246858a18cf2b2272ba7e061785e715002532cafe3a9bce406e3f05f4ca219f02319072ff8e63ed33af0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
